name: ACS Community Packaging CI

on:
  pull_request:
    branches:
      - master
      - release/**
      - feature/**
      - support/**
  push:
    branches:
      - master
      - release/**
      - feature/**
      - support/**
  workflow_dispatch:

env:
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.33.0
      - name: "Build and Test"
        run: mvn -B -U install

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [build]
    if: >
      contains(github.event.head_commit.message, '[release]') &&
      (github.ref_name == 'master' || startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'support/')) &&
      github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.33.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.33.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-author@v1.33.0
        with:
          username: ${{ secrets.BOT_GITHUB_USERNAME }}
          email: ${{ secrets.BOT_GITHUB_EMAIL }}
      - name: "Release"
        timeout-minutes: 60
        run: |
          bash _ci/release.sh
